### ISSUE TITLE
Key bindings not working

### ISSUE THREAD

**Issue by Roofusia235** [tiker/GoGoMount#5]
Recreating issue from curseforge

Keybinding to mount is not working.  Using the same keybind to dismount works just fine, I just can't mount.  

[GoGoMount.txt](https://github.com/tiker/GoGoMount/files/2670436/GoGoMount.txt)

Attaching a new debug file with the latest version installed.

**Comment by tiker** [comment]
You have a rather odd issue.  I don't know what the problem is and can't see why it just stops.

I tried to re-create the exact same scenario you were in with your test in the log above with a level 120 character, in Stormwind, with a single mount as a zone specific favourite but it worked fine for me.

I'm going to create a test version for you that'll generate a lot of spam to find out exactly where it's failing.  I'll post a link to it in the next day or two.

**Comment by Roofusia235** [comment]
Hey, I just wanted to check to see if this is still being looked at.  If not, no big deal but I wanted to know if I should keep waiting.  Thanks!

**Comment by Roofusia235** [comment]
Another data point.  If I'm playing my shaman (haven't tested with other shapeshifting classes yet) and I'm in combat and moving the keybind I have set up for mounting will shift me in to ghost wolf form.  It does not work when out of combat.

**Comment by tiker** [comment]
For the keybinding issue, I have no idea why it is causing an issue for you.  At this point, I'd say the best thing to do is to reset your GoGoMount settings and try it again.  Either delete the GoGoMount.lua file in the saved variables directory for your character or use the "reset to default" / addon only button from the settings screen.

As for your Shaman, I'm assuming you've added some mounts as favorites.  You should see Ghost Wolf form on the list, add it as well.

When you enter combat, GoGoMount sets up a macro with Ghost Wolf in it since it's your only option.  Out of combat, it will use the list of favorites & exclusions if they have been setup.

(I'm going by memory here.  It's been years since I last played a Shaman but I'll verify what I said above this weekend to make sure there isn't a new bug with recent game updates.)

**Comment by Roofusia235** [comment]
Wiping all of the saved variables did the trick.  I uninstalled the addon, deleted the saved variables across all my characters, and reinstalled 8.1.4.  Keybinds are working now.  I don't know why I didn't try this initially but I'm beyond thrilled to have this working again.  Thanks for all the correspondence and the work on this great addon.
